### ISSUE TITLE
Cannot install in Laravel 4 project

### ISSUE THREAD

**Issue by rauanmaemirov** [mvdbos/php-spider#10]
Trying to install with composer in laravel 4 environment, returns:

$composer require vdb/php-spider:dev-master

./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Conclusion: remove symfony/translation 2.3.x-dev
    - Installation request for vdb/php-spider dev-master -> satisfiable by vdb/php-spider[dev-master].
    - Installation request for symfony/finder == 2.3.9999999.9999999-dev -> satisfiable by symfony/finder[2.3.x-dev], symfony/symfony[2.3.x-dev].
    - Conclusion: don't install symfony/translation 2.3.x-dev
    - Can only install one of: symfony/symfony[2.4.x-dev, 2.3.x-dev].
    - don't install symfony/symfony 2.3.x-dev|remove symfony/class-loader 2.4.x-dev
    - don't install symfony/class-loader 2.4.x-dev|don't install symfony/symfony 2.3.x-dev
    - Installation request for symfony/translation == 2.3.9999999.9999999-dev -> satisfiable by symfony/symfony[2.3.x-dev], symfony/translation[2.3.x-dev].
    - Installation request for symfony/class-loader == 2.4.9999999.9999999-dev -> satisfiable by symfony/class-loader[2.4.x-dev], symfony/symfony[2.4.x-dev].

Installation failed, reverting ./composer.json to its original content.

Naturally, I cannot remove components.

**Comment by mvdbos** [comment]
Should work now. I have updated the dependencies.
