### ISSUE TITLE
Authentication

### ISSUE THREAD

**Issue by blalabbla** [mvdbos/php-spider#13]
Hi,
Does it support webform authentication before crawling ? Many websites need to login before letting you access their data.
Thanks

**Comment by crouti** [comment]
same question, does it support authentication ?
Thanks

**Comment by solverat** [comment]
+1

**Comment by JanPetterMG** [comment]
+1
Isn't this as easy as just sending an cookie?
Haven't looked that much into the code yet, but there is a way to set GuzzleHttp options right? (at least it should be, for general usage)

**Comment by solverat** [comment]
hey guys, i found a way to achieve the auth crawl.

**1.) create a class:**
```php
<?php

namespace YourExtension\Crawler\Listener;

use Symfony\Component\EventDispatcher\Event;

class Auth {

    public function setAuth(Event $event) {

        $client = $event->getSubject()->getRequestHandler()->getClient();
        $client->setDefaultOption('auth', array('USERNAME', 'PASS', 'Basic'));
    }

}
```

**2.) add a authentication eventlistener to your spider:**
```php
$authListener = new Listener\Auth();
$spider->getDownloader()->getDispatcher()->addListener(
   SpiderEvents::SPIDER_CRAWL_PRE_REQUEST,
   array($authListener, 'setAuth')
);
```

this should work!
