### ISSUE TITLE
Invalid (Non UTF-8) character in page throws error when retrieving from cache

### ISSUE THREAD

**Issue by carlwhittick** [mvdbos/php-spider#30]
After an object containing an invalid character in its body has been serialized and stored, when it is later retrieved via the persistence handler it throws a fatal error.

**Comment by mvdbos** [comment]
Can you provide me with an example?

**Comment by carlwhittick** [comment]
My apologies upon further investigation it appears the issue is actually occurring in the version of Guzzle being used. Sorry to waste your time!
