### ISSUE TITLE
Limit parse uri with mask

### ISSUE THREAD

**Issue by soulcreate** [mvdbos/php-spider#33]
How I make filter crawl uri by mask?
For example: I need all pages with uri `domain.com/category1/` but don't need pages on uri `domain.com/about/`. How I make this filter?
I check this
```
$spider->getDiscovererSet()->set(new XPathExpressionDiscoverer("//a[@href^='http://domain.com/category1']"));
```
but get php error...

**Comment by soulcreate** [comment]
it is
```
use VDB\Spider\Filter\Prefetch\UriFilter;
...
$spider->getDiscovererSet()->addFilter(new UriFilter(['/about.*/']));
```

**Comment by mvdbos** [comment]
Good to see that you found it.
