### ISSUE TITLE
question: distributed spidering 

### ISSUE THREAD

**Issue by phrazer** [mvdbos/php-spider#34]
will eventually support distributed spidering with a central queue

you have any roadmap when will you implement this? have you tough about how would that work? I would like to help if you need to. 

best,

**Comment by jarodium** [comment]
https://en.wikipedia.org/wiki/Distributed_web_crawling

**Comment by mvdbos** [comment]
As you may have noticed, this project is not very actively maintained. :-) 
I really only do bug fixes and small dependency upgrades to keep it usable. 
I also accept PRs.
