### ISSUE TITLE
FilePersistenceHandler descendants fail with too long file paths

### ISSUE THREAD

**Issue by hranicka** [mvdbos/php-spider#35]
I have a problem with file persisting when the full path is too long.

I'm running on Windows and there is a limit 260 chars per full file path [[source]](http://stackoverflow.com/questions/265769/maximum-filename-length-in-ntfs-windows-xp-and-windows-vista).

Also on other platforms there is a limit. It's 255 chars per file name (not full path which is nearly unlimited).

Here is more explanation of limits per platform/file system: https://en.wikipedia.org/wiki/Comparison_of_file_systems#Limits

---

Current implementations of `\VDB\Spider\PersistenceHandler\FileSerializedResourcePersistenceHandler` and `\VDB\Spider\PersistenceHandler\FileRawResponsePersistenceHandler` makes file name via `urlencode()` of the original full URI. And [it can be longer](http://stackoverflow.com/questions/417142/what-is-the-maximum-length-of-a-url-in-different-browsers) than FS limits.

---

What about replace `urlencode()` with `md5()`, `sha1()` or custom function which make short file name?

I can prepare a PR with it if you agree.

**Comment by mvdbos** [comment]
Thanks for reporting this bug and making the PR. I will not merge the PR and close this issue for the following reasons: 

- If you want different behaviour, you can create your own persistence handler (perhaps extended from the abstract class FilePersistenceHandler or by implementing the PersistenceHandlerInterface).
- I will fix the bug in the FileSerializedResourcePersistenceHandler by giving it wget-like behaviour. I will save resources with their full path by creating a directory structure that mirrors the URI structure.
