### ISSUE TITLE
Abandoned package (guzzle/guzzle)

### ISSUE THREAD

**Issue by lapin-b** [mvdbos/php-spider#37]
Hello,
When I was installing the package with composer, it appears that guzzle/guzzle is abandoned. I mean the package moved to a new name: guzzlehttp/guzzle
I think it's better to copy-paste the install log so you can see what's going on and a picture is 10K words worth
```bash
l4p1n@l4p1n:/var/www/default/sites/mirror-o-matic$ composer require vdb/php-spider
Using version ^0.2.0 for vdb/php-spider
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)

# [Some installing fu]

symfony/event-dispatcher suggests installing symfony/dependency-injection ()
symfony/event-dispatcher suggests installing symfony/http-kernel ()
guzzle/guzzle suggests installing guzzlehttp/guzzle (Guzzle 5 has moved to a new package name. The package you have installed, Guzzle 3, is deprecated.)
Package guzzle/guzzle is abandoned, you should avoid using it. Use guzzlehttp/guzzle instead.
Writing lock file
Generating autoload files
l4p1n@l4p1n:/var/www/default/sites/mirror-o-matic$ 
```
(Note: Writing this post at 2AM and I could have made some stupid misspells or not been clear enough)

**Comment by mvdbos** [comment]
I understand you perfectly :-)

It is true what you say. This is applicable to tag 0.2, which is still the default stable in composer.
This has been fixed in master and will soon be tagged as the new stable 0.3.
