### ISSUE TITLE
Why so many methods are private?

### ISSUE THREAD

**Issue by Chi-teck** [mvdbos/php-spider#40]
I am trying to build own spider upon php-spider and faced the troubles with extending default services because they use private methods (for instance _DiscovererSet_). Is there some special reason for this? Can we make them "protected"?

**Comment by mvdbos** [comment]
I agree some refactoring needs to be done. The DiscovererSet of the Spider should be an interface, just as all its other dependencies, such as the Downloader. I have no time to do this in the foreseeable future, but feel free to make a PR.
