### ISSUE TITLE
support PHP7?

### ISSUE THREAD

**Issue by wujunze** [mvdbos/php-spider#41]
Hello, can you tell me whether the program support PHP7

**Comment by JanPetterMG** [comment]
Yes?
According to the badge in the readme, the build is currently passing for PHP 7.0
https://travis-ci.org/mvdbos/php-spider

**Comment by wujunze** [comment]
OK  thanks

**Comment by solverat** [comment]
btw. does anyone knows something about the current release timeline? the latest release requires guzzle 3, which reached EOL some months ago.
