### ISSUE TITLE
Laravel 5.3 not found class

### ISSUE THREAD

**Issue by Tropicalista** [mvdbos/php-spider#42]
I'm trying to use this package in a laravel 5.3 app. I installed it using composer. 

When I try to instantiate a new spider I get class not found exception.

My composer

```
    "require": {
        "php": ">=5.6.4",
        "laravel/framework": "5.3.*",
        "vdb/php-spider": "^0.2.0",
        "barryvdh/laravel-debugbar": "^2.3"
    },
```

In my controller I have the following:

```
use \VDB\Spider;

class HomeController extends Controller
{
    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $spider = new \VDB\Spider('http://www.dmoz.org');
        return view('home');
    }
}
```

Can you help me? 

thanks

**Comment by bubnovKelnik** [comment]
First, please, read more about namespaces in php5.
You already call
`use \VDB\Spider;`

Why you call `new \VDB\Spider`? It must be `new Spider`.

Second, give full exception message, please.
Do you use composer`s autoloader?

**Comment by Tropicalista** [comment]
Hi, 

thanks for reply. I have fixed the namespace error using:

`use VDB\Spider;`

I made a composer dump-autoload and all it's working right now. 

Thanks
