### ISSUE TITLE
 PHP Fatal error:  Class 'VDB\\Spider\\Spider' not found

### ISSUE THREAD

**Issue by r00tk1ll** [mvdbos/php-spider#43]
I know I must be doing something stupid but I'm getting this error after install php-spider 2 in my document root using composer.json then running example_simple.php from the root directory. The vendor directory gets created but in the subfolder vendor/vdb I only have a folder called "uri".

I tried copying the "Spider" folder from the /src/VDB/ directory to vendor/vdb and creating a folder VDB/ and copying the "Spider" folder there. Still get the same error.

Im using CENTOS 6 with php 5.5 and didn't see any errors when I ran the command  "composer install" in the same directory as composer.json.

What am I doing wrong here?

Thanks

**Comment by mvdbos** [comment]
You should not clone php-spider directly, unless you intend to develop on it. If you want to use it in a project, just include it as a dependency in your composer.json.
