### ISSUE TITLE
is php-spider a abandoned repo?

### ISSUE THREAD

**Issue by solverat** [mvdbos/php-spider#44]
Hi @mvdbos,

because it's a little bit complicated to get in contact with you i'll try it with a issue. :)

php-spider is still the greatest web spider out there but the latest release uses [guzzle 3,  which has reached the EOL](https://github.com/guzzle/guzzle3) months ago. Is there any chance of a new release any time soon? 

it would be great to hear from you and hopefully you get a chance to reply.

thanks

**Comment by mvdbos** [comment]
Hi @solverat,  I currently do not have time to spend on this, and I can't give an indication when that will be the case. But feel free to create a PR for updating the dependencies. If all tests keep working, I will merge it.

**Comment by solverat** [comment]
hey, thanks for your response. for now it would be great if you could tag the master branch or publish a new release to get rid of the guzzle EOL. We're working with the dev-master quite a time and there are no issues.

btw: it would be great to have some contributor over here to handle the open issues here (the most of them are outdated / invalid).

thanks again!

**Comment by mvdbos** [comment]
ok, I have tagged v0.3. It is equal to master.
