### ISSUE TITLE
ErrorException in CrawlerDiscoverer.php line 46: Call to undefined method DOMAttr::getAttribute()

### ISSUE THREAD

**Issue by neorganic** [mvdbos/php-spider#47]
Hello, when trying to get all the a attributes(hrefs), I get the following error:

> ErrorException in CrawlerDiscoverer.php line 46:
> Call to undefined method DOMAttr::getAttribute()

My code that causes the problem:
` $spider->getDiscovererSet()->set(new XPathExpressionDiscoverer("//a/@href"));`
How to resolve this or should I change my query to accomplish my goal ?

**Comment by mvdbos** [comment]
I have made the requirement of needing `ext-dom` php extension explicit in composer.json.
