### ISSUE TITLE
Info

### ISSUE THREAD

**Issue by dearste** [mvdbos/php-spider#50]
Hi, how to implement a search results page with your spider?
There is some example?

Thx.

**Comment by tobiassjosten** [comment]
Did you check [the examples directory](https://github.com/mvdbos/php-spider/tree/master/example)? The [simple example](https://github.com/mvdbos/php-spider/blob/master/example/example_simple.php) covers enough to explain how to solve what you're trying to do.

**Comment by dearste** [comment]
Ok, thanks! I think I can implement my search query on this loop:

```
foreach ($spider->getDownloader()->getPersistenceHandler() as $resource) {
    echo "\n - " . $resource->getCrawler()->filterXpath('//title')->text();
}
```
and find results.

Is also possible to search images?

**Comment by tobiassjosten** [comment]
I think you'd do that with a custom [Discoverer](https://github.com/mvdbos/php-spider/blob/master/src/VDB/Spider/Discoverer/Discoverer.php). It's fed a [Resource](https://github.com/mvdbos/php-spider/blob/master/src/VDB/Spider/Resource.php), from which you could extract whatever information you need.
