### ISSUE TITLE
Confusing separate event dispatchers

### ISSUE THREAD

**Issue by tobiassjosten** [mvdbos/php-spider#51]
Currently, the default queue manager and downloader creates their own separate instances of a event dispatcher. This is very confusing when you try to add listeners to `$spider->getDispatcher()` but it only receives a subset of all the events. Of course you could:

    $spider->getDispatcher()->addListener(…);
    $spider->getDownloader()->getDispatcher()->addListener(…);
    $spider->getQueueManager()->getDispatcher()->addListener(…);

… but then you have to look up which events goes into what subsystem.

I have an idea for a simple fix for this. :) PR to come!

**Comment by mvdbos** [comment]
@tobiassjosten Thanks for giving this thought and taking the time for creating a PR, but I don't agree with your suggestion. See my explanation in PR #52 .
