### ISSUE TITLE
How php-spider work with proxy?

### ISSUE THREAD

**Issue by Chel1982** [mvdbos/php-spider#55]
Can I work with proxies when collecting links?

**Comment by HamzaDevz** [comment]
+1

**Comment by mvdbos** [comment]
If you have the HTTP_PROXY and HTTPS_PROXY environment variables set, they will automatically be picked up and used by the GuzzleRequestHandler. If that does not work for you, you can create your own request handler that is even smarter about it. See #63 for some explanation on how to do that.
