### ISSUE TITLE
Wrong Event Arguments

### ISSUE THREAD

**Issue by solverat** [mvdbos/php-spider#61]
@mvdbos i think your ["Simplify build and clean up use statements"](https://github.com/mvdbos/php-spider/commit/e278cde9c50606fefdbec31ee68a2cbf1f7dc3a1#r33915587) commit introduced some evil changes. :) 

https://github.com/mvdbos/php-spider/blob/b8447e6fa4f8051b35178f3a1905de764dd9625d/src/VDB/Spider/Downloader/Downloader.php#L8

`Symfony\Contracts\EventDispatcher\EventDispatcherInterface` does not exists in S3. Why not using the default `Symfony\Component\EventDispatcher\EventDispatcherInterface`?

https://github.com/mvdbos/php-spider/blob/b8447e6fa4f8051b35178f3a1905de764dd9625d/src/VDB/Spider/Downloader/Downloader.php#L94

=> Wrong argument order (event name has to be the first argument)

https://github.com/mvdbos/php-spider/blob/b8447e6fa4f8051b35178f3a1905de764dd9625d/src/VDB/Spider/QueueManager/InMemoryQueueManager.php#L85

=> Wrong argument order (event name has to be the first argument)

https://github.com/mvdbos/php-spider/blob/b8447e6fa4f8051b35178f3a1905de764dd9625d/src/VDB/Spider/Spider.php#L230

=> Wrong argument order (event name has to be the first argument)

**Comment by solverat** [comment]
@mvdbos for reference:
https://symfony.com/blog/new-in-symfony-4-3-simpler-event-dispatching#supporting-both-dispatchers

**Comment by mvdbos** [comment]
Unfortunately using that EventDispatcherProxy won't work if your composer.json forces the 3.x version of the Dispatcher: that class won't be availabe then. :-)

Luckily, the normal eventdispatcher from S4 also has BC support for the order of the arguments, so I will revert back to that. 

By the time S5 is released in November, this BC support will be dropped. Then I will have to swap the arguments and drop support for S3.

**Comment by mvdbos** [comment]
I have just released 0.4.1. Can you confirm that it is fixed now?

**Comment by solverat** [comment]
Hey @mvdbos, I just tested it locally and everything is working fine now! Thanks!
