### ISSUE TITLE
Is it possible to count/track the number of links pointing to a page?

### ISSUE THREAD

**Issue by spekulatius** [mvdbos/php-spider#64]
Hello @mvdbos 

really neat library. I'm using it crawl my own page and build a comprehensive sitemap from it. I was wondering, if it is possible to count/track the number of links pointing to a page?

Cheers,
Peter

**Comment by mvdbos** [comment]
Well, you could probably use an event listener or persistence handler to save encountered links  to some sort of database and query that? This lib is primarily for fetching everything, the rest you can add yourself.

**Comment by spekulatius** [comment]
Yeah, that's an idea. Event listener sounds like a good approach - I'll give it a try
