### ISSUE TITLE
How can I pass a form like login or signup?

### ISSUE THREAD

**Issue by msHanObject** [mvdbos/php-spider#65]
I want to give information about the user which expected to pass the form to spider.

How can I do this?

**Comment by mvdbos** [comment]
Can you clarify? It is not clear to me what you are trying to do.

**Comment by solverat** [comment]
I guess he's trying to do something like this: https://github.com/mvdbos/php-spider/issues/13.

**Comment by msHanObject** [comment]
> I guess he's trying to do something like this: #13.

I used your code and I rust my test code.
But in my case, the crawler stopped right a way.
I uploaded my code file below.

[test.txt](https://github.com/mvdbos/php-spider/files/4387307/test.txt)

'Auth.php' file is just same as your code.

**Comment by mvdbos** [comment]
See 844a94e1b7269cd6c54214b071366848447aec49 for an example that may work better.
