### ISSUE TITLE
URL with Port number issue

### ISSUE THREAD

**Issue by eddiejaoude** [mvdbos/php-spider#7]
If the url contains a port number, i.e. mydomain.com:8080, it appears this gets dropped? Is this correct or is there config for this?

**Comment by mvdbos** [comment]
A bit late this reply... Almost 7 years.

Anyway, this should have worked back then as well. To prove it, I have added a test that show that is works. See here: https://github.com/mvdbos/php-spider/blob/master/tests/VDB/Spider/Tests/Discoverer/DiscovererSetTest.php#L93

This test asserts that two links are discovered and is succesful. One of these links has a port number.
