### ISSUE TITLE
Pass Query Parameters

### ISSUE THREAD

**Issue by MahmoudSaidHaggag** [mvdbos/php-spider#84]
how to pass Query Params with all Crawling links

Sample for this
https://example.com?locale=en
https://example.com/blog/details/1?locale=en

I want this, to handle crawling with multi languages sites

Can help me please

**Comment by MahmoudSaidHaggag** [comment]
Hi, @mvdbos 

Can help me please

**Comment by mvdbos** [comment]
Hi @MahmoudSaidHaggag, you can add some middleware to the Guzzle client that does this on every request. The Guzzle docs contain an example for adding a request header [here](https://docs.guzzlephp.org/en/stable/handlers-and-middleware.html#middleware). This example could be easily modified to do what you want. 

[Line 93](https://github.com/mvdbos/php-spider/blob/master/example/example_complex.php#L93) of the complex example shows how you can get access to the Guzzle client:

```php
$guzzleClient = $spider->getDownloader()->getRequestHandler()->getClient();
```

**Comment by mvdbos** [comment]
I added an example that demonstrate how to do it even simpler than with custom Guzzle middleware. It simply sets a custom Guzzle client on the spider and configures Guzzle to always set some query params: https://github.com/mvdbos/php-spider/blob/master/example/example_persistent_request_params.php
