### ISSUE TITLE
install problems

### ISSUE THREAD

**Issue by aggied** [mvdbos/php-spider#9]
I'm not a PhD in php here but composer is having issues installing this on my machine. Very interested in seeing what you have put together with your spider...

I don't have curl installed as I'm just testing this on my local Windows 7 machine running xampp, but when I run the command in composer 

<pre>php composer.phar require vdb/php-spider
Please provide a version constraint for the way/generators requirement: 0.1.*</pre>

I'm told the <pre>vdb/uri dev-master</pre> can't be found. 

I've tried installing this from a clone, but no luck...

any thoughts?

<b>Update</b>
Just re-shifted some things and now I'm getting this error in the example_simple.php

Fatal error: Call to undefined function VDB\Spider\pcntl_signal() in C:\xampp\htdocs\test\src\VDB\Spider\Spider.php on line 98

**Comment by mvdbos** [comment]
Should be fixed now.
